### ISSUE TITLE
overNumber seems to be offset be 1 

### ISSUE THREAD

**Issue by kaushithamsilva** [cepdnaclk/e19-co226-Database-for-Cricket-Statistics#10]
eg: if actual overnumber == 0.5, the server send 1.5 instead

**Comment by KATTA-00** [comment]
Over number should start from 0 in the Db

**Comment by kaushithamsilva** [comment]
Still not configured. @SanduniU issue still open.

**Comment by KATTA-00** [comment]
frontEnd should display the data,
backEnd sending
overNum = 1,2,3...
ballNum = 1-6

**Comment by kaushithamsilva** [comment]
Done.
Note: When entering data please start from overNum 0
