### ISSUE TITLE
Extras Object does not show individual entries

### ISSUE THREAD

**Issue by kaushithamsilva** [cepdnaclk/e19-co226-Database-for-Cricket-Statistics#12]
Extras object shows the total extras correctly but does not show any data for individual extra types. please fix it.

**Comment by KATTA-00** [comment]
{
    totalRuns: null,
    innings: 2,
    teamId: 2,
    wickets: 0,
    overNum: 0,
    ballNumber: 0,
    extras: { total: 0, wides: 0, noBalls: 0, legByes: 0, byes: 0 },
    isBatting: false
  }

you mean this extras??

**Comment by KATTA-00** [comment]
When entering the db format should be,
wides 
noBalls 
legByes
 byes
