### ISSUE TITLE
match-score overnumber and ballnumber issue on the 6th ball

### ISSUE THREAD

**Issue by kaushithamsilva** [cepdnaclk/e19-co226-Database-for-Cricket-Statistics#13]
This is only for the match-score socket.  Do not change the match-status socket or the commentary

For the last ball of the over .i.e the 6th ball eg: 1.6 overs --> should be shown as 2.0 instead of 1.6
the domain for ballNumber therefore should be (0-5). ball number of 6 makes no sense.

**Comment by KATTA-00** [comment]
eka uba hadala ganin front eken ona widiyata.....

**Comment by kaushithamsilva** [comment]
uba maara manussayek neh. close karanna epa oi issue eka ehema kiyala. man hithuwa wadeh hari kiyala

**Comment by KATTA-00** [comment]
ehenm hadala close karapan 🤣
