### ISSUE TITLE
4s and 6s not shown in the scorecard

### ISSUE THREAD

**Issue by kaushithamsilva** [cepdnaclk/e19-co226-Database-for-Cricket-Statistics#15]
4s and 6s for batsman's scores for both innings are not shown.

**Comment by KATTA-00** [comment]
In the views the column names should be fours and sixes not 6s and 4s

**Comment by kaushithamsilva** [comment]
issue not fixed, so opened again, assigned to Sanduni

**Comment by SanduniU** [comment]
4s and 6s are already in the batsmanScores view as 'fours' and 'sixes'

**Comment by KATTA-00** [comment]
please update the latest commits

**Comment by kaushithamsilva** [comment]
Works on the frontEnd now! Fixed, closing issue
