### ISSUE TITLE
bowler's wides and no balls should not be included in their ball count

### ISSUE THREAD

**Issue by kaushithamsilva** [cepdnaclk/e19-co226-Database-for-Cricket-Statistics#17]
if bowler bowls a wide, it should not be counted as a ball. for example if bowler bowls only 1 over and he bowls two wides, the scorecard of bowler should show only 1.0 as the number of overs bowled. but currently it says 1.2 instead counting the wides and noballs. 

note: Byes and LegByes are counted. only wides and no balls should be neglected.

**Comment by KATTA-00** [comment]
@SanduniU

**Comment by SanduniU** [comment]
SELECT
        CurrentBowlerID,
        COUNT(CASE WHEN Ball_ID IN (SELECT Ball_ID FROM EXTRAINNINGS1 
                                    WHERE Type = 'byes' OR Type = 'legByes') 
                                    THEN Ball_ID 
                                    ELSE NULL END) AS ballsBowled
    FROM INNINGS1
    GROUP BY CurrentBowlerID
Query changed
