### ISSUE TITLE
Incorrect Maidens Values

### ISSUE THREAD

**Issue by kaushithamsilva** [cepdnaclk/e19-co226-Database-for-Cricket-Statistics#18]
In the bowlingfigures views, the number of maidens is wrong.

**Comment by KATTA-00** [comment]
@SanduniU

**Comment by SanduniU** [comment]
SELECT
        CurrentBowlerID,
        COUNT(DISTINCT OverNum) AS MaidenOvers
    FROM INNINGS2
    WHERE NOT EXISTS (
        SELECT 1
        FROM INNINGS2 AS I
        WHERE I.CurrentBowlerID = INNINGS2.CurrentBowlerID
          AND I.OverNum = INNINGS2.OverNum
          AND I.RunsScored > 0
query changed

**Comment by kaushithamsilva** [comment]
Just checking, shouldn't this change for both innings? Also can you change it on the .sql file on the db directory so i can update in my localhost as well.

**Comment by SanduniU** [comment]
I have changed both queries and updated it in the battingviews.sql file

**Comment by KATTA-00** [comment]
please update the latest commints

**Comment by kaushithamsilva** [comment]
Fixed, works perfectly. Closing Issue
