### ISSUE TITLE
onStrike Batsman Incorrect

### ISSUE THREAD

**Issue by kaushithamsilva** [cepdnaclk/e19-co226-Database-for-Cricket-Statistics#8]
onStrike batsman should be the person facing the next ball not the ball before. Currently it shows the batsman who faced the previous ball. 

This can be somewhat fixed if runs scored is checked to be even or odd and check the end of over condition

if (runsScored % 2 == 0 && ballNumber != 6)  {
    newOnStikeBatsman = prevOnStrikeBatsman
} else if  (runsScored % 2 == 1 && ballNumber !=6) {
    newOnStrikeBatsman = prevNonStrikeBatman
} else if (runScored ballNumber == 6...... //you get the idea... )....

**Comment by KATTA-00** [comment]
checking for 

if (playing.RunsScored % 2 == 0 && playing.BallNumber != 6)
        onStrike = playing.OnStrikeID;
else if (playing.RunsScored % 2 == 1 && playing.BallNumber != 6)
        onStrike = playing.NonStrikeID;
else if(playing.BallNumber == 6)
        onStrike = playing.NonStrikeID;

**Comment by KATTA-00** [comment]
if (playing.RunsScored % 2 == 0 && playing.BallNumber != 6)
        onStrike = playing.OnStrikeID;
        else if (playing.RunsScored % 2 == 1 && playing.BallNumber != 6)
        onStrike = playing.NonStrikeID;
        else if(playing.BallNumber == 6 && playing.RunsScored % 2 == 0)
        onStrike = playing.NonStrikeID;
        else if(playing.BallNumber == 6 && playing.RunsScored % 2 == 1)
        onStrike = playing.OnStrikeID;
